# Generated by Django 3.1.7 on 2021-04-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.CreateModel(
            name='QuizImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=1024)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='quizz_app.quiz')),
            ],
            options={
                'verbose_name': 'Изображение для викторин',
                'verbose_name_plural': 'Изображения для викторин',
            },
        ),
    ]
